name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      # Add this step to print environment variables in the runner BEFORE the SWA deploy action
      - name: Print Runner Environment Variables Before SWA Action
        run: |
          echo "--- Runner Environment Variables Before SWA Action ---"
          printenv | grep VITE_API_URL || echo "VITE_API_URL not found in environment"
          echo "----------------------------------------------------"

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_CALM_BUSH_07397DB10 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "./frontend" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "dist" # Built app content directory - optional

          # Keep the explicit app_build_command from the last step
          app_build_command: |
            echo "--- Frontend Build Environment Variables (inside build command) ---"
            echo "VITE_API_URL is: $VITE_API_URL"
            echo "-----------------------------------------------------------------"
            cd $APP_LOCATION
            npm install --legacy-peer-deps || yarn install --ignore-engines
            npm run build || yarn build

          ###### End of Repository/Build Configurations ######

      close_pull_request_job:
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        runs-on: ubuntu-latest
        name: Close Pull Request Job
        steps:
          - name: Close Pull Request
            id: closepullrequest
            uses: Azure/static-web-apps-deploy@v1
            with:
              azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_CALM_BUSH_07397DB10 }}
              action: "close"
